import { useMemo, useState } from 'react';
import { ArrowRight, ChevronDown, MapPin, Menu, MessageCircle, Phone, X } from 'lucide-react';
const phone='03265300826'; const whatsapp=`https://wa.me/${phone}`;
const materials=[
{title:'White Marble',eyebrow:'Light • Veined',tone:'light',text:'Clean white stone with natural movement for bright, refined spaces.'},
{title:'Veined Marble',eyebrow:'Expressive • Natural',tone:'silver',text:'Character-rich veining for statement surfaces and feature areas.'},
{title:'Premium Marble',eyebrow:'Soft • Elegant',tone:'cream',text:'Warm, elegant stone for floors, walls, kitchens and interiors.'},
{title:'Black Stone',eyebrow:'Bold • Dramatic',tone:'dark',text:'Deep-toned stone with striking veins for high-contrast designs.'}];
function App(){const[open,setOpen]=useState(false);const[showFlyer,setShowFlyer]=useState(false);const[material,setMaterial]=useState('All');const nav=useMemo(()=>['Home','Collection','About','Locations','Contact'],[]);const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};return <div className="site"><header className="nav-wrap"><nav className="nav shell"><button className="brand" onClick={()=>go('home')} aria-label="Ismail Marble & Granite home"><span className="brand-mark">IM</span><span><strong>ISMAIL</strong><small>MARBLE & GRANITE</small></span></button><div className={`links ${open?'open':''}`}>{nav.map(item=><button key={item} onClick={()=>go(item.toLowerCase())}>{item}</button>)}<a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp</a></div><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav></header>
<main><section id="home" className="hero shell"><div className="hero-copy"><p className="kicker">LAHORE • WHOLESALE DEALER</p><h1>Natural stone with <em>presence.</em></h1><p className="hero-text">Marble and granite slabs selected for homes, businesses and architectural spaces. Talk directly with Toqeer Ahmad for your stone requirements.</p><div className="hero-actions"><button className="btn primary" onClick={()=>go('collection')}>Explore collection <ArrowRight size={17}/></button><a className="btn ghost" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp us</a></div><div className="micro"><span>01</span><b>MARBLE</b><span>02</span><b>GRANITE</b><span>03</span><b>WHOLESALE</b></div></div><div className="hero-visual"><div className="stone-card stone-white"><span>01 / WHITE</span><div className="vein v1"/><div className="vein v2"/></div><div className="stone-card stone-black"><span>02 / BLACK</span><div className="dark-vein"/></div><div className="visual-note"><span>ISMAIL</span><strong>MARBLE<br/>& GRANITE</strong></div></div></section>
<section className="intro-band"><div className="shell band-grid"><p>From subtle whites to dramatic dark stone.</p><span>Natural variation is part of the material.</span></div></section>
<section id="collection" className="section shell"><div className="section-head"><div><p className="kicker">THE COLLECTION</p><h2>Stone for spaces<br/><em>with character.</em></h2></div><p className="section-lead">The current collection is based on the materials visible in our supplied business information. Exact stone names, prices and specifications can be confirmed directly.</p></div><div className="filter-row">{['All','Marble','Granite'].map(x=><button className={material===x?'filter active':'filter'} key={x} onClick={()=>setMaterial(x)}>{x}</button>)}</div><div className="cards">{materials.filter(m=>material==='All'||(material==='Granite'?m.title==='Black Stone':m.title!=='Black Stone')).map((m,i)=><article className={`material ${m.tone}`} key={m.title}><div className="material-image"><span>0{i+1}</span><div className="texture"/></div><div className="material-body"><p>{m.eyebrow}</p><h3>{m.title}</h3><span>{m.text}</span></div></article>)}</div></section>
<section id="about" className="section dark-section"><div className="shell about-grid"><div><p className="kicker">ABOUT THE BUSINESS</p><h2>A direct, local route to <em>natural stone.</em></h2></div><div className="about-copy"><p>Ismail Marble & Granite is presented as a wholesale dealer serving Lahore. The business contact shown on the flyer is Toqeer Ahmad, making direct WhatsApp communication the clearest route for availability and requirements.</p><div className="facts"><div><strong>WHOLESALE</strong><span>Dealer</span></div><div><strong>LAHORE</strong><span>Based locations</span></div><div><strong>DIRECT</strong><span>WhatsApp inquiry</span></div></div></div></div></section>
<section className="process shell"><div className="section-head compact"><div><p className="kicker">A SIMPLE PROCESS</p><h2>Bring us your <em>requirement.</em></h2></div></div><div className="steps"><div><span>01</span><h3>Tell us what you need</h3><p>Share the material, look, quantity or project use.</p></div><div><span>02</span><h3>Discuss availability</h3><p>Connect with Toqeer Ahmad on WhatsApp for current options.</p></div><div><span>03</span><h3>Select your stone</h3><p>Review suitable slabs and move forward with your order.</p></div></div></section>
<section id="locations" className="locations"><div className="shell"><div className="section-head compact"><div><p className="kicker">FIND US IN LAHORE</p><h2>Two convenient <em>locations.</em></h2></div><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Ismail+Marble+%26+Granite+Lahore" target="_blank" rel="noreferrer">Ask for directions <ArrowRight size={16}/></a></div><div className="location-grid"><article><div className="loc-num">01</div><MapPin/><h3>Saqib Town • Main Bedian Road</h3><p>Near KIA Showroom, Saqib Town, Main Bedian Road, Lahore.</p><a className="location-link" href="https://www.google.com/maps/search/?api=1&query=KIA+Showroom+Saqib+Town+Main+Bedian+Road+Lahore" target="_blank" rel="noreferrer">Open in Google Maps <ArrowRight size={14}/></a></article><article><div className="loc-num">02</div><MapPin/><h3>Ring Road • DHA Phase 5</h3><p>Service Road near DHA Phase 5, M Block, Lahore.</p><a className="location-link" href="https://www.google.com/maps/search/?api=1&query=Ring+Road+Service+Road+DHA+Phase+5+M+Block+Lahore" target="_blank" rel="noreferrer">Open in Google Maps <ArrowRight size={14}/></a></article></div></div></section>
<section id="contact" className="contact shell"><div className="contact-panel"><div><p className="kicker">LET'S TALK STONE</p><h2>Have a requirement?<br/><em>Let's discuss it.</em></h2><p>For current stock, stone options and wholesale inquiries, contact Toqeer Ahmad directly.</p></div><div className="contact-actions"><a className="btn primary" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Chat on WhatsApp</a><a className="phone" href={`tel:${phone}`}><Phone size={17}/> 0326-5300826</a></div></div></section>
<section className="flyer-section shell"><button className="flyer-toggle" onClick={()=>setShowFlyer(!showFlyer)}>{showFlyer?'Hide original flyer':'View original business flyer'} <ChevronDown size={16} className={showFlyer?'rot':''}/></button>{showFlyer&&<div className="flyer-frame"><img src="/resources/ismail-marble-granite-flyer.jpg" alt="Original Ismail Marble & Granite business flyer"/></div>}</section></main>
<footer><div className="shell footer-grid"><div><button className="brand footer-brand" onClick={()=>go('home')}><span className="brand-mark">IM</span><span><strong>ISMAIL</strong><small>MARBLE & GRANITE</small></span></button><p>Wholesale marble & granite dealer in Lahore.</p></div><div className="footer-links">{nav.slice(1).map(item=><button key={item} onClick={()=>go(item.toLowerCase())}>{item}</button>)}</div><div className="footer-contact"><span>Toqeer Ahmad</span><a href={whatsapp} target="_blank" rel="noreferrer">0326-5300826</a></div></div><div className="shell copyright"><span>© Ismail Marble & Granite</span><span>Lahore, Pakistan</span></div></footer></div>}
export default App;
